/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java20032567;
import java.awt.*;
import java.io.*;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author 6609504
 */
public class TestFile extends javax.swing.JFrame {

    /**
     * Creates new form eiei
     */
    public TestFile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnWriteFile = new javax.swing.JButton();
        txtLink = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        TxtManuName = new javax.swing.JTextField();
        txtPicture = new javax.swing.JTextField();
        txtMenuID = new javax.swing.JTextField();
        btnShowOutput = new javax.swing.JButton();
        btnCreateFile2 = new javax.swing.JButton();
        btnShowPicture = new javax.swing.JButton();
        btnOpenFile = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnWriteFile.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnWriteFile.setText("Write File");
        btnWriteFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWriteFileActionPerformed(evt);
            }
        });

        txtLink.setColumns(10);
        txtLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLinkActionPerformed(evt);
            }
        });

        txtLocation.setColumns(15);
        txtLocation.setToolTipText("");

        TxtManuName.setColumns(8);
        TxtManuName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtManuNameActionPerformed(evt);
            }
        });

        txtPicture.setColumns(10);
        txtPicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPictureActionPerformed(evt);
            }
        });

        txtMenuID.setColumns(10);
        txtMenuID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMenuIDActionPerformed(evt);
            }
        });

        btnShowOutput.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnShowOutput.setText("Show Out Put");
        btnShowOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowOutputActionPerformed(evt);
            }
        });

        btnCreateFile2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnCreateFile2.setText("Create File");
        btnCreateFile2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateFile2ActionPerformed(evt);
            }
        });

        btnShowPicture.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnShowPicture.setText("Show Picture");
        btnShowPicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowPictureActionPerformed(evt);
            }
        });

        btnOpenFile.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnOpenFile.setText("Open File");
        btnOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenFileActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        txtOutput.setColumns(20);
        txtOutput.setRows(5);
        jScrollPane1.setViewportView(txtOutput);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(btnCreateFile2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(txtMenuID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(16, 16, 16)
                                                .addComponent(TxtManuName))
                                            .addComponent(txtPicture, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(106, 106, 106)
                                                    .addComponent(btnWriteFile)
                                                    .addGap(0, 0, Short.MAX_VALUE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(57, 57, 57)
                                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                                                    .addComponent(btnShowPicture)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(203, 203, 203)
                                                .addComponent(btnShowOutput))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtLink, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnOpenFile)
                                        .addGap(4, 4, 4)))
                                .addGap(196, 196, 196))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCreateFile2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMenuID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtManuName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(btnWriteFile)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPicture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btnShowOutput)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnShowPicture)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOpenFile)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLinkActionPerformed

    private void TxtManuNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtManuNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtManuNameActionPerformed

    private void txtPictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPictureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPictureActionPerformed

    private void txtMenuIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMenuIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMenuIDActionPerformed
     

    private void btnShowOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowOutputActionPerformed
        // TODO add your handling code here:
         try {
      File myObj = new File(txtLocation.getText());
      Scanner myReader = new Scanner(myObj);
      while (myReader.hasNextLine()) {
         data += myReader.nextLine()+ "\n";
      }
      myReader.close();
       txtOutput.setText(data);
    } catch (FileNotFoundException e) {
        JOptionPane.showMessageDialog(rootPane, "An error occurred.");
}

        
         

    }//GEN-LAST:event_btnShowOutputActionPerformed
        File myObj;
        String data = "";
        String petName = "";
    private void btnCreateFile2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateFile2ActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        int returnValue  = fc.showSaveDialog(this);
        if(returnValue == JFileChooser.APPROVE_OPTION)
        {
            File file = fc.getSelectedFile();
            txtLocation.setText(file.getAbsolutePath());        
        try {
        File myObj = new File(txtLocation.getText());
        if (myObj.createNewFile()) {
        JOptionPane.showMessageDialog(rootPane, "File created: " + myObj.getName());
        } else {
          JOptionPane.showMessageDialog(rootPane, "File already exists.");
        }
        } catch (Exception e) {
          JOptionPane.showMessageDialog(rootPane, "An error occurred.");
        }
          }
          else
              JOptionPane.showMessageDialog(rootPane, "Create File Command cancelled by user");
    }//GEN-LAST:event_btnCreateFile2ActionPerformed

    private void btnShowPictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowPictureActionPerformed
        // TODO add your handling code here:
         ImageIcon myimg = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource(petName)));
         Image img1 = myimg.getImage();         
         Image img2 = img1.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
         ImageIcon i = new ImageIcon(img2);
         jLabel1.setIcon(i);

    }//GEN-LAST:event_btnShowPictureActionPerformed

    private void btnOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenFileActionPerformed
        // TODO add your handling code here:
          File file;
        try
{
          file = new File(txtLocation.getText());
   
         if(!Desktop.isDesktopSupported()){
            JOptionPane.showMessageDialog(null,"Desktop is not supported");
            return;
        }
        
        Desktop desktop = Desktop.getDesktop();
        if(file.exists()) desktop.open(file);
      }
        catch(Exception e)
        {
        } 

    }//GEN-LAST:event_btnOpenFileActionPerformed

    private void btnWriteFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWriteFileActionPerformed
        // TODO add your handling code here:
         try {
            FileWriter writer = new FileWriter(txtLocation.getText(), true);            
            BufferedWriter bufferedWriter = new BufferedWriter(writer);
            bufferedWriter.newLine();
           
            bufferedWriter.write(txtMenuID.getText() + "," + TxtManuName.getText()
            + "," + txtPicture.getText()+ "," + txtLink.getText());
            String x = txtPicture.getText();
            int indx = x.lastIndexOf('\\');
            petName =  x.substring(indx+1);
            jTextField1.setText(petName);
            bufferedWriter.close();        

            } catch (IOException e) {
             JOptionPane.showMessageDialog(rootPane, "An error occurred.");
        }

    }//GEN-LAST:event_btnWriteFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestFile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtManuName;
    private javax.swing.JButton btnCreateFile2;
    private javax.swing.JButton btnOpenFile;
    private javax.swing.JButton btnShowOutput;
    private javax.swing.JButton btnShowPicture;
    private javax.swing.JButton btnWriteFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtLink;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtMenuID;
    private javax.swing.JTextArea txtOutput;
    private javax.swing.JTextField txtPicture;
    // End of variables declaration//GEN-END:variables
}
